### ISSUE TITLE
FIFO threshold max

### ISSUE THREAD

**Issue by stepanurban** [sparkfun/SparkFun_LSM6DS3_Arduino_Library#13]
Hi,
there is a wrong range in settings.fifoThreshold value in comment. Correct range is: 0 to 4095 not 4096.

Steven

**Comment by edspark** [comment]
You are correct, [fixed](https://github.com/sparkfun/SparkFun_LSM6DS3_Arduino_Library/commit/99f7af4435eac1b9f2ce4ceafc61fe02b5deaa7d)
