### ISSUE TITLE
Library configuration doesn't work

### ISSUE THREAD

**Issue by stepanurban** [sparkfun/SparkFun_LSM6DS3_Arduino_Library#14]
Setting configuration to some other values than default doesn't work
For example
myIMU.settings.accelEnabled = 0
will not turn off accelerometer.
myIMU.settings.fifoModeWord = 1
works only for 6
etc.

**Comment by edspark** [comment]
Keep in mind that settings must be set before you call `begin()` and can not be changed on the fly as they are applied only when the `begin()` function is called (at least for now). I added the settings you mentioned and they applied correctly. 
![image](https://user-images.githubusercontent.com/18684691/140985996-311b861a-6153-4670-84ad-2c6e3f4d8586.png)
Sorry for the non-verbose serial output.
