### ISSUE TITLE
Spikes in Gyro data

### ISSUE THREAD

**Issue by lalitheranti** [sparkfun/SparkFun_LSM6DS3_Arduino_Library#15]
Hi, 
I see lot of spikes in the gyro data with the settings, like this 👍 
`
	settings.gyroEnabled = 1;  //Can be 0 or 1
	settings.gyroRange = 1000;   //Max deg/s.  Can be: 125, 245, 500, 1000, 2000
	settings.gyroSampleRate = 6660;   //Hz.  Can be: 13, 26, 52, 104, 208, 416, 833, 1666
	settings.gyroBandWidth = 400;  //Hz.  Can be: 50, 100, 200, 400;
	settings.gyroFifoEnabled = 1;  //Set to include gyro in FIFO
	settings.gyroFifoDecimation = 1;  //set 1 for on /1

	settings.accelEnabled = 1;
	settings.accelODROff = 1;
	settings.accelRange = 2;      //Max G force readable.  Can be: 2, 4, 8, 16
	settings.accelSampleRate = 6660;  //Hz.  Can be: 13, 26, 52, 104, 208, 416, 833, 1666, 3332, 6664, 13330
	settings.accelBandWidth = 400;  //Hz.  Can be: 50, 100, 200, 400;
	settings.accelFifoEnabled = 1;  //Set to include accelerometer in the FIFO
	settings.accelFifoDecimation = 1;  //set 1 for on /1

	settings.tempEnabled = 1;

	//Select interface mode
	settings.commMode = 1;  //Can be modes 1, 2 or 3

	//FIFO control data
	settings.fifoThreshold = 3000;  //Can be 0 to 4096 (16 bit bytes)
	settings.fifoSampleRate = 6600;  //default 10Hz
	settings.fifoModeWord = 0;  //Default off

	allOnesCounter = 0;
	nonSuccessCounter = 0;`

is there any suggestion or filter settings, or something I should change?

**Comment by edspark** [comment]
Sorry that I'm so late to reply. This type of question is best suited to our [forums](https://forum.sparkfun.com/viewforum.php?f=83&sid=2ff38862da31f96c543a654676892695). If it hasn't already been touched upon there, please open a new topic!
