### ISSUE TITLE
Not combining MSB and LSB

### ISSUE THREAD

**Issue by washcycle** [sparkfun/SparkFun_LSM6DS3_Arduino_Library#2]
Is there any particular reason that the MSB and LSB aren't being combined for the signal data? Or maybe it is and I am not seeing it?

**Comment by marshalltaylorSFE** [comment]
What line of what file are you referring to?  I'll take a look.

**Comment by washcycle** [comment]
I did more digging and it looks okay, took awhile to follow what was going on. 

`readRegisterInt16` seems to handle this discretely , the `length` parameter set to `2` tells it to read the MSB then increment the pointer and read the LSB into an array.

I was looking for something similar to this `(msb << 8) | lsb` method.
