### ISSUE TITLE
FifoExample compilation failed on Arduino Nano 33 IoT

### ISSUE THREAD

**Issue by vlasov01** [sparkfun/SparkFun_LSM6DS3_Arduino_Library#20]
Hi,

I'm using Arduino Nano 33 IoT which has LSM6DS3.
I've tried LowLevelExample.ino and it is working fine. I need only change LSM6DS3Core I2C address to 0x6A.
I'd like to try FifoExample, but got compilation error.

I'm using a Arduino CLI nightly build to compile. Here is my command line:
arduino-cli compile -b arduino:samd:nano_33_iot FifoExample33IOT -v

`C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:60:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.gyroEnabled = 1;  //Can be 0 or 1
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:61:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.gyroRange = 2000;   //Max deg/s.  Can be: 125, 245, 500, 1000, 2000
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:62:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.gyroSampleRate = 833;   //Hz.  Can be: 13, 26, 52, 104, 208, 416, 833, 1666
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:63:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.gyroBandWidth = 200;  //Hz.  Can be: 50, 100, 200, 400;
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:64:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.gyroFifoEnabled = 1;  //Set to include gyro in FIFO
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:65:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.gyroFifoDecimation = 1;  //set 1 for on /1
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:67:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.accelEnabled = 1;
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:68:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.accelRange = 16;      //Max G force readable.  Can be: 2, 4, 8, 16
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:69:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.accelSampleRate = 833;  //Hz.  Can be: 13, 26, 52, 104, 208, 416, 833, 1666, 3332, 6664, 13330
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:70:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.accelBandWidth = 200;  //Hz.  Can be: 50, 100, 200, 400;
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:71:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.accelFifoEnabled = 1;  //Set to include accelerometer in the FIFO
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:72:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.accelFifoDecimation = 1;  //set 1 for on /1
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:73:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.tempEnabled = 1;
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:76:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.commMode = 1;
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:79:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.fifoThreshold = 100;  //Can be 0 to 4096 (16 bit bytes)
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:80:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.fifoSampleRate = 50;  //Hz.  Can be: 10, 25, 50, 100, 200, 400, 800, 1600, 3300, 6600
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:81:9: error: 'class LSM6DS3Core' has no member named 'settings'
   myIMU.settings.fifoModeWord = 6;  //FIFO mode.
         ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:95:13: error: 'class LSM6DS3Core' has no member named 'begin'; did you mean 'beginCore'?
   if( myIMU.begin() != 0 )
             ^~~~~
             beginCore
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:105:9: error: 'class LSM6DS3Core' has no member named 'fifoBegin'
   myIMU.fifoBegin();
         ^~~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:109:9: error: 'class LSM6DS3Core' has no member named 'fifoClear'
   myIMU.fifoClear();
         ^~~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino: In function 'void loop()':
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:120:18: error: 'class LSM6DS3Core' has no member named 'fifoGetStatus'
   while( ( myIMU.fifoGetStatus() & 0x8000 ) == 0 ) {};  //Wait for watermark
                  ^~~~~~~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:125:18: error: 'class LSM6DS3Core' has no member named 'fifoGetStatus'
   while( ( myIMU.fifoGetStatus() & 0x1000 ) == 0 ) {
                  ^~~~~~~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:127:16: error: 'class LSM6DS3Core' has no member named 'calcGyro'
   temp = myIMU.calcGyro(myIMU.fifoRead());
                ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:127:31: error: 'class LSM6DS3Core' has no member named 'fifoRead'
   temp = myIMU.calcGyro(myIMU.fifoRead());
                               ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:131:16: error: 'class LSM6DS3Core' has no member named 'calcGyro'
   temp = myIMU.calcGyro(myIMU.fifoRead());
                ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:131:31: error: 'class LSM6DS3Core' has no member named 'fifoRead'
   temp = myIMU.calcGyro(myIMU.fifoRead());
                               ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:135:16: error: 'class LSM6DS3Core' has no member named 'calcGyro'
   temp = myIMU.calcGyro(myIMU.fifoRead());
                ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:135:31: error: 'class LSM6DS3Core' has no member named 'fifoRead'
   temp = myIMU.calcGyro(myIMU.fifoRead());
                               ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:139:16: error: 'class LSM6DS3Core' has no member named 'calcAccel'
   temp = myIMU.calcAccel(myIMU.fifoRead());
                ^~~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:139:32: error: 'class LSM6DS3Core' has no member named 'fifoRead'
   temp = myIMU.calcAccel(myIMU.fifoRead());
                                ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:143:16: error: 'class LSM6DS3Core' has no member named 'calcAccel'
   temp = myIMU.calcAccel(myIMU.fifoRead());
                ^~~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:143:32: error: 'class LSM6DS3Core' has no member named 'fifoRead'
   temp = myIMU.calcAccel(myIMU.fifoRead());
                                ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:147:16: error: 'class LSM6DS3Core' has no member named 'calcAccel'
   temp = myIMU.calcAccel(myIMU.fifoRead());
                ^~~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:147:32: error: 'class LSM6DS3Core' has no member named 'fifoRead'
   temp = myIMU.calcAccel(myIMU.fifoRead());
                                ^~~~~~~~
C:\Users\admin\Documents\Arduino\FifoExample33IOT\FifoExample33IOT.ino:155:24: error: 'class LSM6DS3Core' has no member named 'fifoGetStatus'
   tempUnsigned = myIMU.fifoGetStatus();
                        ^~~~~~~~~~~~~
Using library SparkFun_LSM6DS3_Breakout at version 1.0.0 in folder: C:\Users\admin\Documents\Arduino\libraries\SparkFun_LSM6DS3_Breakout
Using library Wire at version 1.0 in folder: C:\Users\admin\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.11\libraries\Wire
Using library SPI at version 1.0 in folder: C:\Users\admin\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.11\libraries\SPI

Error during build: exit status 1`

Regards,

Sergey

**Comment by edspark** [comment]
This is a bit of a stale issue. I have tried compiling in the Arduino IDE for Arduino NANO 33 IOT and it compiles a-ok. This sounds specifically related to the Arduino CLI and so is more appropriate as an issue for that environment and not this library.
