### ISSUE TITLE
interfacing lsm6ds3 with esp32

### ISSUE THREAD

**Issue by Goutham8128** [sparkfun/SparkFun_LSM6DS3_Arduino_Library#3]

**Comment by Goutham8128** [comment]
Hi

I want to interface lsm6ds3 with esp32. Can i get any source?

**Comment by zencuke** [comment]
I've been looking at the library and I see no reason it wouldn't work with esp32 as is. It just uses i2c or spi which are both supported with esp32. You just need to figure out which pins to connect.

**Comment by edspark** [comment]
Sorry for the late reply. I have made a number of changes to the library that allow the ESP32 to interface with this product. You can find the specific changes here if you're interested: https://github.com/sparkfun/SparkFun_LSM6DS3_Arduino_Library/commit/9eb64645716cd161ec8019648a7e572c0b32202d.
